# Generated by Django 3.0.2 on 2020-02-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('m', 'механика'), ('a', 'автомат'), ('r', 'робот')], default='manual', verbose_name='Коробка передач'),
        ),
    ]
