# Generated by Django 3.0.2 on 2020-02-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_auto_20200210_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('m', 'механика'), ('a', 'автомат'), ('r', 'робот')], default='a', max_length=1, verbose_name='Коробка передач'),
        ),
    ]
